# This is the file used to process the data for the project

In [80]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
from pandas_datareader import data as pdr

In [81]:
# Download data from Yahoo Finance
tickers = ["SPY", "QQQ", "IWM"]
data = yf.download(tickers, start="2005-01-01", end="2025-10-01", auto_adjust=True)

# Display the first 10 rows of the data
data.head()

[*********************100%***********************]  3 of 3 completed

Price           Close                             High                        \
Ticker            IWM        QQQ        SPY        IWM        QQQ        SPY
Date
2005-01-03  48.436916  33.738789  81.847130  49.422176  34.413565  82.840453
2005-01-04  47.398586  33.123783  80.846992  48.569529  33.943766  82.010405
2005-01-05  46.451256  32.918819  80.289108  47.474410  33.277560  81.132751
2005-01-06  46.697544  32.756512  80.697357  47.140910  33.064005  81.064752
2005-01-07  46.178383  32.927341  80.581665  46.951433  33.200668  81.119149

Price             Low                             Open                        \
Ticker            IWM        QQQ        SPY        IWM        QQQ        SPY
Date
2005-01-03  48.179233  33.627749  81.574985  49.335020  34.242735  82.704378
2005-01-04  47.315218  32.927330  80.581653  48.531637  33.883973  81.955975
2005-01-05  46.451256  32.859029  80.282303  47.345570  33.038399  80.785767
2005-01-06  46.401964  32.747972  80.459233  46.739226  32.995675  80.581697
2005-01-07  46.151857  32.636932  80.370750  46.803645  32.935885  80.942254

Price         Volume
Ticker           IWM        QQQ       SPY
Date
2005-01-03  16062600  100970900  55748000
2005-01-04  27450000  136623200  69167600
2005-01-05  29884200  127925500  65667300
2005-01-06  23061200  102934600  47814700
2005-01-07  20906200  123104000  55847700

In [82]:
# Download VIX data from FRED
vix = pdr.DataReader("VIXCLS", "fred", start="2005-01-01", end="2025-10-01")
vix.head()

            VIXCLS
DATE
2005-01-03   14.08
2005-01-04   13.98
2005-01-05   14.09
2005-01-06   13.58
2005-01-07   13.49

In [83]:
# Make sure VIX column name is nice
vix = vix.rename(columns={"VIXCLS": "VIX"})

# Align by Date index and keep only overlapping trading days
master_df = pd.concat([data, vix], axis=1).dropna(subset=["VIX"])

master_df.head(10)

,"(Close, IWM)","(Close, QQQ)","(Close, SPY)","(High, IWM)","(High, QQQ)","(High, SPY)","(Low, IWM)","(Low, QQQ)","(Low, SPY)","(Open, IWM)","(Open, QQQ)","(Open, SPY)","(Volume, IWM)","(Volume, QQQ)","(Volume, SPY)",VIX
2005-01-03,48.436916,33.738789,81.847130,49.422176,34.413565,82.840453,48.179233,33.627749,81.574985,49.335020,34.242735,82.704378,16062600.0,100970900.0,55748000.0,14.08
2005-01-04,47.398586,33.123783,80.846992,48.569529,33.943766,82.010405,47.315218,32.927330,80.581653,48.531637,33.883973,81.955975,27450000.0,136623200.0,69167600.0,13.98
2005-01-05,46.451256,32.918819,80.289108,47.474410,33.277560,81.132751,46.451256,32.859029,80.282303,47.345570,33.038399,80.785767,29884200.0,127925500.0,65667300.0,14.09
2005-01-06,46.697544,32.756512,80.697357,47.140910,33.064005,81.064752,46.401964,32.747972,80.459233,46.739226,32.995675,80.581697,23061200.0,102934600.0,47814700.0,13.58
2005-01-07,46.178383,32.927341,80.581665,46.951433,33.200668,81.119149,46.151857,32.636932,80.370750,46.803645,32.935885,80.942254,20906200.0,123104000.0,55847700.0,13.49
2005-01-10,46.648285,32.910267,80.962662,47.065125,33.200677,81.275626,46.193551,32.790687,80.513623,46.231445,32.833394,80.513623,23449000.0,88764200.0,56563300.0,13.23
2005-01-11,46.079857,32.679661,80.404800,46.447435,32.884657,80.785800,45.947226,32.517374,80.275531,46.417119,32.773617,80.717765,23233800.0,106398800.0,63099700.0,13.19
2005-01-12,46.269348,32.952976,80.670097,46.420927,32.970056,80.853792,45.572088,32.466110,79.955719,46.148085,32.824853,80.554438,24791200.0,127754900.0,72720500.0,12.56
2005-01-13,46.129124,32.517361,80.023758,46.561122,33.183594,80.778956,45.909334,32.466111,79.942113,46.341333,32.952977,80.717721,18940600.0,101982400.0,55537500.0,12.84
2005-01-14,46.568699,32.824852,80.445580,46.648277,32.901725,80.642884,46.167017,32.619855,80.119010,46.265541,32.628399,80.261885,13541000.0,93460900.0,42032500.0,12.43

In [84]:
master_df.shape

(5246, 16)

In [85]:
master_df.columns

Index([ ('Close', 'IWM'),  ('Close', 'QQQ'),  ('Close', 'SPY'),
         ('High', 'IWM'),   ('High', 'QQQ'),   ('High', 'SPY'),
          ('Low', 'IWM'),    ('Low', 'QQQ'),    ('Low', 'SPY'),
         ('Open', 'IWM'),   ('Open', 'QQQ'),   ('Open', 'SPY'),
       ('Volume', 'IWM'), ('Volume', 'QQQ'), ('Volume', 'SPY'),
                   'VIX'],
      dtype='object')

In [86]:
print(master_df.dtypes)

(Close, IWM)     float64
(Close, QQQ)     float64
(Close, SPY)     float64
(High, IWM)      float64
(High, QQQ)      float64
(High, SPY)      float64
(Low, IWM)       float64
(Low, QQQ)       float64
(Low, SPY)       float64
(Open, IWM)      float64
(Open, QQQ)      float64
(Open, SPY)      float64
(Volume, IWM)    float64
(Volume, QQQ)    float64
(Volume, SPY)    float64
VIX              float64
dtype: object

In [87]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5246 entries, 2005-01-03 to 2025-10-01
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   (Close, IWM)   5219 non-null   float64
 1   (Close, QQQ)   5219 non-null   float64
 2   (Close, SPY)   5219 non-null   float64
 3   (High, IWM)    5219 non-null   float64
 4   (High, QQQ)    5219 non-null   float64
 5   (High, SPY)    5219 non-null   float64
 6   (Low, IWM)     5219 non-null   float64
 7   (Low, QQQ)     5219 non-null   float64
 8   (Low, SPY)     5219 non-null   float64
 9   (Open, IWM)    5219 non-null   float64
 10  (Open, QQQ)    5219 non-null   float64
 11  (Open, SPY)    5219 non-null   float64
 12  (Volume, IWM)  5219 non-null   float64
 13  (Volume, QQQ)  5219 non-null   float64
 14  (Volume, SPY)  5219 non-null   float64
 15  VIX            5246 non-null   float64
dtypes: float64(16)
memory usage: 696.7 KB

In [88]:
master_df.describe()

,"(Close, IWM)","(Close, QQQ)","(Close, SPY)","(High, IWM)","(High, QQQ)","(High, SPY)","(Low, IWM)","(Low, QQQ)","(Low, SPY)","(Open, IWM)","(Open, QQQ)","(Open, SPY)","(Volume, IWM)","(Volume, QQQ)","(Volume, SPY)",VIX
count,5219.000000,5219.000000,5219.000000,5219.000000,5219.000000,5219.000000,5219.000000,5219.000000,5219.000000,5219.000000,5219.000000,5219.000000,5.219000e+03,5.219000e+03,5.219000e+03,5246.000000
mean,112.153879,156.157094,220.712708,113.056347,157.244319,221.902754,111.173879,154.901753,219.339940,112.174984,156.124481,220.676114,4.221027e+07,6.512213e+07,1.236422e+08,19.154785
std,56.854061,143.515251,149.983143,57.296438,144.488142,150.691734,56.405300,142.367778,149.109846,56.881346,143.486082,149.936915,2.808088e+07,5.133049e+07,9.048368e+07,8.681422
min,27.389328,22.087286,50.092159,28.384869,23.055114,51.482178,27.285791,21.646574,49.349356,27.660115,22.476144,49.974483,1.200000e+03,7.079300e+06,1.527000e+07,9.140000
25%,59.796955,42.118679,98.508083,60.463995,42.448539,99.104040,59.236591,41.841264,97.906684,59.923789,42.165002,98.533175,2.400715e+07,3.079885e+07,6.525730e+07,13.420000
50%,100.630814,97.469612,171.110291,101.406662,97.981501,171.778030,99.878962,96.754713,170.052634,100.601495,97.404646,170.963204,3.392370e+07,4.812380e+07,9.264070e+07,16.700000
75%,153.388969,252.795181,304.979965,154.156125,254.875688,306.520297,152.624086,249.613095,303.847899,153.356452,252.019253,304.857734,5.196715e+07,8.257675e+07,1.518524e+08,22.155000
max,244.839996,602.200012,666.840027,247.179993,602.869995,667.340027,243.440002,597.719971,662.169983,245.570007,602.369995,666.719971,3.551170e+08,6.167723e+08,8.710263e+08,82.690000

In [89]:
# Check for missing values col by col
missing_per_col = master_df.isna().sum().sort_values(ascending=False)
print(missing_per_col.head(30))

(Close, IWM)     27
(Close, QQQ)     27
(Close, SPY)     27
(High, IWM)      27
(High, QQQ)      27
(High, SPY)      27
(Low, IWM)       27
(Low, QQQ)       27
(Low, SPY)       27
(Open, IWM)      27
(Open, QQQ)      27
(Open, SPY)      27
(Volume, IWM)    27
(Volume, QQQ)    27
(Volume, SPY)    27
VIX               0
dtype: int64

In [90]:
# Check for missing values row by row
missing_per_day = master_df.isna().sum(axis=1)
print("Days with any missing values:", (missing_per_day > 0).sum())
print(missing_per_day[missing_per_day > 0].head())

Days with any missing values: 27
2022-05-30    15
2022-06-20    15
2022-07-04    15
2022-09-05    15
2022-11-24    15
dtype: int64

In [91]:
# drop the rows with only VIX
master_df = master_df.dropna(subset=[('Close', 'IWM')])
master_df['Date'] = master_df.index
master_df = master_df.reset_index(drop=True)
master_df['Date'] = pd.to_datetime(master_df['Date'], format='%Y-%m-%d')
master_df.head()

,"(Close, IWM)","(Close, QQQ)","(Close, SPY)","(High, IWM)","(High, QQQ)","(High, SPY)","(Low, IWM)","(Low, QQQ)","(Low, SPY)","(Open, IWM)","(Open, QQQ)","(Open, SPY)","(Volume, IWM)","(Volume, QQQ)","(Volume, SPY)",VIX,Date
0,48.436916,33.738789,81.847130,49.422176,34.413565,82.840453,48.179233,33.627749,81.574985,49.335020,34.242735,82.704378,16062600.0,100970900.0,55748000.0,14.08,2005-01-03
1,47.398586,33.123783,80.846992,48.569529,33.943766,82.010405,47.315218,32.927330,80.581653,48.531637,33.883973,81.955975,27450000.0,136623200.0,69167600.0,13.98,2005-01-04
2,46.451256,32.918819,80.289108,47.474410,33.277560,81.132751,46.451256,32.859029,80.282303,47.345570,33.038399,80.785767,29884200.0,127925500.0,65667300.0,14.09,2005-01-05
3,46.697544,32.756512,80.697357,47.140910,33.064005,81.064752,46.401964,32.747972,80.459233,46.739226,32.995675,80.581697,23061200.0,102934600.0,47814700.0,13.58,2005-01-06
4,46.178383,32.927341,80.581665,46.951433,33.200668,81.119149,46.151857,32.636932,80.370750,46.803645,32.935885,80.942254,20906200.0,123104000.0,55847700.0,13.49,2005-01-07

In [92]:
# Clean up the column names - remove tuples and create simpler names
new_columns = []
for col in master_df.columns:
    col = str(col)
    if col[0] == "(":
        # Remove parentheses and split
        clean_col = col.strip('()').replace("'", "").replace('"', '')
        parts = clean_col.split(', ')
        # Format as 'IWM_Close'
        new_columns.append(f"{parts[1]}_{parts[0]}")
    else:
        new_columns.append(col)

master_df.columns = new_columns
master_df.head()

,IWM_Close,QQQ_Close,SPY_Close,IWM_High,QQQ_High,SPY_High,IWM_Low,QQQ_Low,SPY_Low,IWM_Open,QQQ_Open,SPY_Open,IWM_Volume,QQQ_Volume,SPY_Volume,VIX,Date
0,48.436916,33.738789,81.847130,49.422176,34.413565,82.840453,48.179233,33.627749,81.574985,49.335020,34.242735,82.704378,16062600.0,100970900.0,55748000.0,14.08,2005-01-03
1,47.398586,33.123783,80.846992,48.569529,33.943766,82.010405,47.315218,32.927330,80.581653,48.531637,33.883973,81.955975,27450000.0,136623200.0,69167600.0,13.98,2005-01-04
2,46.451256,32.918819,80.289108,47.474410,33.277560,81.132751,46.451256,32.859029,80.282303,47.345570,33.038399,80.785767,29884200.0,127925500.0,65667300.0,14.09,2005-01-05
3,46.697544,32.756512,80.697357,47.140910,33.064005,81.064752,46.401964,32.747972,80.459233,46.739226,32.995675,80.581697,23061200.0,102934600.0,47814700.0,13.58,2005-01-06
4,46.178383,32.927341,80.581665,46.951433,33.200668,81.119149,46.151857,32.636932,80.370750,46.803645,32.935885,80.942254,20906200.0,123104000.0,55847700.0,13.49,2005-01-07

In [93]:
# Save the master_df to a csv file
master_df.to_csv("master_df.csv", index=False)